name: Build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup dependencies
        run: |
          sudo apt update
          sudo apt install -y rpm libarchive-tools
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - name: build non-main
        if: ${{ github.ref != 'refs/heads/main' }}
        run: npm run build:no-publish
